---
fixtures:
  repositories:
    stdlib:
      ref: "v6.0.0"
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib"
    concat:
      ref: "v6.1.0"
      repo: "https://github.com/puppetlabs/puppetlabs-concat"
    rsnapshot:
      ref: "1.2.4"
      repo: "https://github.com/loomsen/puppet-rsnapshot"
  symlinks:
    vision_rsnapshot: '#{source_dir}'
