---
fixtures:
    repositories:
        concat: "https://github.com/puppetlabs/puppetlabs-concat"
        stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib"
        rsnapshot: "https://github.com/loomsen/puppet-rsnapshot"
    symlinks:
        vision_rsnapshot: '#{source_dir}'
